### ISSUE TITLE
Issue with boolean false argument

### ISSUE THREAD

**Issue by SamuelGD** [palantir/conjure-typescript#87]
## What happened?

Hi Conjure team,
I have an API with an endpoint where 1 url parameter is a boolean.

Problem: when using conjure-typescript and using _false_ for the argument, false is transformed into an empty string - while _true_ remains "true".

```
await getXXXService(configuration).setYYYState(
                false
            );
```
=> transforms false into an empty string in the URL.

Conjure definition:
```      setYYYState:
        http: POST /zzzzz/{state}
        args:
          state:
            type: boolean
            param-type: path
            markers:
              - Safe
```

API query when state is true:
`POST /api/zzzzz/true`

API query when state is false:
`POST /api/zzzzz/`

My temporary solution: force "false" as a string but it's against the enforced boolean type.

## What did you want to happen?

false should become _"false"_ and not _""_.

Can you please confirm the issue?

Thanks,
Samuel

**Comment by alxhill** [comment]
@ferozco does our analysis look correct here? Seen this before?

Specifically, we're seeing that and endpoint with a boolean path param works when the value is true, but has an empty string when the value is set to false. Happy to make a PR to fix if you can point us in the right direction!

**Comment by SamuelGD** [comment]
I confirm it works with the new version. Closing the issue. Thanks for your help
