### ISSUE TITLE
Expect octet-stream data for optional<binary> responses

### ISSUE THREAD

**Issue by carterkozak** [palantir/conjure-typescript#88]
## What happened?
The generator handles `returns: binary` properly, but expects base64 json for `returns: optional<binary>`

## What did you want to happen?

`optional<binary>` should expect either `application/octet-stream` data, or 204.
See the specification for this case: https://github.com/palantir/conjure/blob/master/docs/spec/wire.md#32-response-body

**Comment by dansanduleac** [comment]
Fixed in #105
